import '../globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import SideNav from '@/components/sidenav';
import MarginWidthWrapper from '@/components/margin-width-wrapper';
import PageWrapper from '@/components/page-wrapper';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Admin Dashboard',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body class_name={`bg-white${inter.class_name}`}>
      <div class_name="flex">
          <SideNav />
          <ToastContainer />
          <main class_name="flex-1">
            <MarginWidthWrapper>
              <PageWrapper>{children}</PageWrapper>
            </MarginWidthWrapper>
          </main>
        </div>
      </body>
    </html>
  );
}